- name: datatypes
  hosts: localhosts
  vars:
    Course: devops with aws
    Tools: 
    - linus
    - aws
    - devops
    Experience:
      devops: 2
      aws: 1
    RealProject: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course{{Course}} tools learned {{Tools}} project experience {{Experience}} real{{RealProject}}"
