- name: variables
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "enter number {{number}} is less than 10"
    when: number < 10
     