- name: intall packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.debug:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql', state: 'latest'}  
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}