- name: variable preference
  hosts: localhost
  vars:
    wishes: "from play-level"
  vars_files: 
  - decl-var.yaml
  - name: prompt level
    prompt: please enter wishes
    private: false
  tasks:
  - name: check preference
    vars:
      wishes: "from task play-level"
      ansible.builtin.debug:
        msg: "{{wishes}}"      